name: working with secrets and variables

on:
    push:
    workflow_dispatch:


env:
    APP_VERSION: 1.0.0
    APP_NAME: my-app
    Environment: production

jobs:
    basic-env-vars:
        runs-on: ubuntu-latest
        env:
            APP_CLASS: my-app-class
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Print environment variables
              run: |
                echo "APP_VERSION: ${{ env.APP_VERSION }}"
                echo "APP_NAME: ${{ env.APP_NAME }}"
                echo "Environment: ${{ env.Environment }}"
                echo "APP_CLASS: ${{ env.APP_CLASS }}"
    
    basic-env-vars2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Print Git variables
              run: |
                echo "APP_VERSION: ${{ env.APP_VERSION }}"
                echo "APP_NAME: ${{ env.APP_NAME }}"
                echo "Environment: ${{ env.Environment }}"
    
    basic-git-variables:
        runs-on: ubuntu-latest
        needs: ["basic-env-vars", "basic-env-vars2"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Print Git variables
              run: |
                echo "REPOSITORY: ${{ vars.REPOSITORY }}"
                echo "REF: ${{ vars.REF }}"
                echo "SHA: ${{ vars.SHA }}"
                echo "ACTOR: ${{ vars.ACTOR }}"
                echo "EVENT_NAME: ${{ vars.EVENT_NAME }}"
                echo "SECRET: ${{ secrets.MY_SECRET }}"