name: working with secrets and variables

on:
  push:
  workflow_dispatch:
    


env:
  App_version: 1.0.0
  App_name: my-app
  Environment: production


jobs:
  basic-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Print environment variables
        run: |
          echo "App Version: ${{ env.App_version }}"
          echo "App Name: ${{ env.App_name }}"
          echo "Environment: ${{ env.Environment }}"

  basic-env-vars2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Print environment variables
        run: |
          echo "App Version: ${{ env.App_version }}"
          echo "App Name: ${{ env.App_name }}"
          echo "Environment: ${{ env.Environment }}"

