name: Conditional-workflow

on:
  workflow_dispatch:
    inputs:
      simulate_failure:
        description: 'Simulate a failure in the workflow'
        type: boolean
        required: false
        default: false

      target_branch:
          description: 'Target branch for the workflow'
          type: string
          required: true
          default: main

  push:
      branches:
        - main
        - develop

jobs:
 Conditional-demo:
  name: Conditional-steps
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Always Run
      run: echo "This step always runs"

    - name: conditional step run only on main branch
      if: github.ref == 'refs/heads/main'
      run: echo "This step runs only on the main branch"   

    
    - name: Only run on non-main branch

      if: github.ref != 'refs/heads/main'

      run: echo "This step runs only on non-main branches"

    - name: Run only on push event

      if: github.event_name == 'push'

      run: echo "This step runs only on push events"

    - name: Run only on workflow_dispatch event

      if: github.event_name == 'workflow_dispatch'

      run: |

          echo "This step runs only on workflow_dispatch events"

          echo "Simulate failure input value: ${{ github.event.inputs.simulate_failure }}"

          echo "Target branch input value: ${{ github.event.inputs.target_branch }}"

          echo "This was triggered manually by ${{ github.actor }}" 
